### ISSUE TITLE
GitHub releases with downloadable data

### ISSUE THREAD

**Issue by klokan** [pnorman/osmborder#3]
Paul, thanks for working on this! Great project. This ticket is an idea for improvement, which should be easy to do.

What about to start to make GitHub "release" for major versions this project?

Maybe the ready-to-use processed data (SHP/CSV/...) from the release could be attached to the release instead of placing it on your private "legolas" server?

See:
https://help.github.com/articles/distributing-large-binaries/ 
The limit is 2 GB per file, which should be fine for this project.

You get a reliable and fast download service for the produced data this way. We use it on OSMNames.org too.

**Comment by pnorman** [comment]
> What about to start to make GitHub "release" for major versions this project?

The data changes with OSM data, not with tagged versions of the software. It's the same as with the coastline data, it gets generated with the same software each time.
